repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-ast
      - id: check-added-large-files

  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: python -m pylint src
        language: system
        types: [python]
        require_serial: true

  - repo: local
    hooks:
      - id: tests
        name: tests
        entry: python -m unittest
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
