repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-ast
      - id: check-added-large-files

  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black

  # - repo: https://github.com/pycqa/pylint
  #   rev: v2.13.0
  #   hooks:
  #   -   id: pylint
  - repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: python -m pylint
        language: system
        types: [python]
        require_serial: true
